### PR TITLE
#138 table of contents (Security & Bash) 

### PR DESCRIPTION
**Pull request by iskandarzulkarnaien**
Adds table of contents (toc) to articles without one and hides them except for mobile and print view as discussed in #138 . 

This PR affects the below chapters under `Other Topics`. Kindly use the below checklist for reviewing.

Items to test for each chapter:
- [ ] Web view (Expected: in-article toc absent)
- [ ] Mobile view (Expected: in-article toc present and **links clickable**, right nav panel absent)
- [ ] Print view (Expected: in-article toc present, left and right nav panels absent)

Chapters:
- [ ] Cross Site Request Forgery
- [ ] Cross Site Scripting
- [ ] Cryptography
- [ ] HTTPS
- [ ] Password Storage
- [ ] SQL Injection
- [ ] Bash

Devtools shortcuts
Firefox:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>

Chrome:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>

### CODE REVIEW

**Comment by iskandarzulkarnaien** [comment]
@anubh-v , @niqiukun would appreciate a review if you guys have the time. Thanks!

**Comment by niqiukun** [comment]
For some reason on the Cross Site Scripting page, the ToC on the side view gets cropped out by the screen. I'm not sure if it is because of my laptop?

image

**Comment by damithc** [comment]
> For some reason on the Cross Site Scripting page, the ToC on the side view gets cropped out by the screen. I'm not sure if it is because of my laptop?

Same for me. Perhaps the MarkBind team can look into this? @le0tan

**Comment by iskandarzulkarnaien** [comment]
@niqiukun Is everything else good to go other than the issue with the XSS page?

**Review by anubh-v — APPROVED** [review]
The table of contents work as described. (Tested on Chrome version 80).

A slight nit pick in the Password Storage article:
1. Click on the "Getting Started"  option in the right nav panel
2. The page navigates to the "Getting Started" section
3. The right nav panel places emphasis on the "Other Resources" option, rather than placing emphasis on the "Getting Started" section

See below:
Peek 2020-04-03 23-04

**Comment by iskandarzulkarnaien** [comment]
Thanks for the help @anubh-v 

>
>     3. The right nav panel places emphasis on the "Other Resources" option, rather than placing emphasis on the "Getting Started" section

I think this is an "issue" with Markbind. Seems like it behaves this way since the sections are rather short, and more than one heading can be on the viewer's screen at the same time. @le0tan just bringing this to your attention. Its a really minor thing.

**Review by niqiukun — APPROVED** [review]
LGTM!

**Comment by iskandarzulkarnaien** [comment]
@niqiukun @anubh-v thanks for all the help!

@damithc this PR is ready to be merged

**Pull request merged**
