### PR TITLE
#138 table of contents (App Frameworks)

### PR DESCRIPTION
**Pull request by iskandarzulkarnaien**
Adds table of contents (toc) to articles without one and hides them except for mobile and print view as discussed in #138 . 

This PR affects the below chapters under `App Frameworks`. Kindly use the below checklist for reviewing.

Items to test for each chapter:
- [ ] Web view (Expected: in-article toc absent)
- [ ] Mobile view (Expected: in-article toc present and **links clickable**, right nav panel absent)
- [ ] Print view (Expected: in-article toc present, left and right nav panels absent)

Chapters:
- [ ] Android
- [ ] Angular
- [ ] iOS
- [ ] Node
- [ ] React
- [ ] Ruby on Rails
- [ ] Vue

Devtools shortcuts
Firefox:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>

Chrome:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>

### CODE REVIEW

**Review by Tejas2805 — APPROVED** [review]
LGTM!

**Comment by damithc** [comment]
Let me know when ready to merge

**Review by nbriannl — APPROVED** [review]
All looks good, tested. Do you intend to rebase over the new master and add TOCs on new chapters recently this sem (eg: Redux)? 

Alternatively you could do a separate PR for those.

**Comment by iskandarzulkarnaien** [comment]
@nbriannl I'm planning to do a final sweep once everyone else's PRs have been merged to make sure all the articles have a ToC and that the ToCs follow TitleCase.

**Comment by iskandarzulkarnaien** [comment]
@Tejas2805 , @nbriannl Thanks for the help guys!

@damithc this PR is ready to be merged, thanks!

**Pull request merged**
