### PR TITLE
Refining UX Design skills

### PR DESCRIPTION
**Pull request by junkiattan**
Wrote on tactics to improve UX design skills, including potential pitfalls and their solutions

Welcoming any reviews;)

### CODE REVIEW

**Review by alexfjw — COMMENTED** [review]
Not really familiar with UX, so I'll just give some general comments. 
- Overall helpful chapter for newbies to UX like me, content is not difficult to understand
- Nice that you have many links, makes it easier to get started
- Might be good to add a table of contents
- A link, or mention of a case study of a good UX project experience might help flesh out your points as well

**Comment by junkiattan** [comment]
@alexfjw Thanx for the feedback! I have added some success case studies as well as table of contents to the section.

**Comment by junkiattan** [comment]
@damithc Could I get your approval on this? Thanx prof!

**Review by damithc — CHANGES_REQUESTED** [review]
Looks good 👍 
This page should be linked from the ToC page.

**Comment by junkiattan** [comment]
@damithc 

I have linked the chapter to the ToC 👍

**Pull request merged**
