### PR TITLE
[#189, #116] Fix mixed content resources error

### LINKED ISSUE #189: Insecure mixed content warning
Netlify is giving this warning for every build of this repo.

image

### PR DESCRIPTION
**Pull request by jamessspanggg**
FIxes #189 and #116

### CODE REVIEW

**Comment by jamessspanggg** [comment]
@damithc The warning no longer occurs now. I believe it's fine to include those images as local resources as two of them are merely screenshots and the other one is from a research paper that we provided references to:
Screen Shot 2020-04-14 at 1 58 00 AM

**Comment by damithc** [comment]
got his again today. 🤔 
image

Was the fix overwritten by a later PR?

**Comment by jamessspanggg** [comment]
> Was the fix overwritten by a later PR?

The changes were not overwritten in the master branch tho 😕

**Comment by jamessspanggg** [comment]
@damithc was it from the master branch or the preview of other PRs?

**Comment by damithc** [comment]
Ah, it's from a PR. I guess no issue then. Will report if it comes again.

**Pull request merged**
