### PR TITLE
#138 table of contents (SE Tools and Other Topics(Com Vision to MultiThreading)) 

### PR DESCRIPTION
**Pull request by iskandarzulkarnaien**
Adds table of contents (toc) to articles without one and hides them except for mobile and print view as discussed in #138 . 

This PR affects the below chapters under `SE Tools` and `Other Topics`. Kindly use the below checklist for reviewing.

Items to test for each chapter:
- [ ] Web view (Expected: in-article toc absent)
- [ ] Mobile view (Expected: in-article toc present and **links clickable**, right nav panel absent)
- [ ] Print view (Expected: in-article toc present, left and right nav panels absent)

Chapters:
- [ ] Regular Expressions
- [ ] Docker
- [ ] Computer Vision
- [ ] DBMS
- [ ] SQL
- [ ] Machine Learning
- [ ] GPGPU
- [ ] CUDA

Devtools shortcuts
Firefox:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>

Chrome:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>

### CODE REVIEW

**Comment by iskandarzulkarnaien** [comment]
@ang-zeyu , @hcwong would appreciate a review from you guys if you could spare the time. Thanks!

**Review by ang-zeyu — APPROVED** [review]
Chapters:
- [x] Regular Expressions
- [x] Docker
- [x] Computer Vision
- [x] DBMS
- [x] SQL
- [x] Machine Learning
- [x] GPGPU
- [x] CUDA

All the links work 👍 It's responsive on all pages as well

**Review by hcwong — APPROVED** [review]
looks good 👍

**Comment by iskandarzulkarnaien** [comment]
Thanks @ang-zeyu and @hcwong for the help!

@damithc this PR is ready to be merged

**Pull request merged**
