### PR TITLE
#138 table of contents (SE Topics: Architecture to Scalability)

### PR DESCRIPTION
**Pull request by iskandarzulkarnaien**
Adds table of contents (toc) to articles without one and hides them except for mobile and print view as discussed in #138 . 

This PR affects the below chapters under `SE Topics`. Kindly use the below checklist for reviewing.

Items to test for each chapter:
- [ ] Web view (Expected: in-article toc absent)
- [ ] Mobile view (Expected: in-article toc present and **links clickable**, right nav panel absent)
- [ ] Print view (Expected: in-article toc present, left and right nav panels absent)

Chapters:
- [ ] REST
- [ ] Code Quality Metrics
- [ ] Documentation
- [ ] Functional Programming
- [ ] Introduction to Performance Optimization
- [ ] Performance Profiling
- [ ] Web Performance
- [ ] Agile Development
- [ ] DevOps
- [ ] Best Practices with git
- [ ] Scalability

Devtools shortcuts
Firefox:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>

Chrome:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>

### CODE REVIEW

**Comment by ang-zeyu** [comment]
Chapters:
- [x] REST
- [x] Code Quality Metrics
- [x] Documentation
- [x] Functional Programming
- [x] Introduction to Performance Optimization
- [x] Performance Profiling
- [x] Web Performance
- [x] Agile Development
- [ ] DevOps
  - The 3 links starting from `code development & review` don't work
- [x] Best Practices with git
- [x] Scalability

Links and ux responsiveness looks good 👍,  just 3 links that don't work in the DevOps article

**Comment by iskandarzulkarnaien** [comment]
> 
> 
> Chapters:
> 
>     * [x]  REST
> 
>     * [x]  Code Quality Metrics
> 
>     * [x]  Documentation
> 
>     * [x]  Functional Programming
> 
>     * [x]  Introduction to Performance Optimization
> 
>     * [x]  Performance Profiling
> 
>     * [x]  Web Performance
> 
>     * [x]  Agile Development
> 
>     * [ ]  DevOps
>       
>       * The 3 links starting from `code development & review` don't work
> 
>     * [x]  Best Practices with git
> 
>     * [x]  Scalability
> 
> 
> Links and ux responsiveness looks good 👍, just 3 links that don't work in the DevOps article

Good catch, thanks for the help! Have fixed it

**Comment by iskandarzulkarnaien** [comment]
I've removed the redundant first link of every toc as per @dvrylc 's suggestion

**Review by ang-zeyu — APPROVED** [review]

**Comment by iskandarzulkarnaien** [comment]
@daekoon could you review if you have the time thanks!

**Comment by daekoon** [comment]
Testing it out, sorry for the super late review

Items to test for each chapter:
- [x] Web view (Expected: in-article toc absent)
- [x] Mobile view (Expected: in-article toc present and **links clickable**, right nav panel absent)
- [x] Print view (Expected: in-article toc present, left and right nav panels absent)

Chapters:
- [x] REST
- [x] Code Quality Metrics
- [x] Documentation
- [x] Functional Programming
- [x] Introduction to Performance Optimization
- [x] Performance Profiling
- [x] Web Performance
- [x] Agile Development
- [x] DevOps
- [x] Best Practices with git
- [x] Scalability

Devtools shortcuts
Firefox:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>

Chrome:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>

**Review by daekoon — APPROVED** [review]
Tested all out on Chrome, on all 3 view modes. Looks good!

**Comment by iskandarzulkarnaien** [comment]
Thanks @daekoon and @ang-zeyu !

@damithc this PR is ready to be merged

**Pull request merged**
