### PR TITLE
#138 table of contents (JS/Kotlin)

### PR DESCRIPTION
**Pull request by iskandarzulkarnaien**
Adds table of contents (toc) to articles without one and hides them except for mobile and print view as discussed in #138 . 

This PR affects the below chapters under `Programming Languages`. Kindly use the below checklist for reviewing.

Items to test for each chapter:
- [ ] Web view (Expected: in-article toc absent)
- [ ] Mobile view (Expected: in-article toc present and **links clickable**, right nav panel absent)
- [ ] Print view (Expected: in-article toc present, left and right nav panels absent)

Chapters:
- [ ] Writing Testable JavaScript Code
- [ ] Javascript Promises
- [ ] Javascript Modules
- [ ] Static Typing in JavaScript
- [ ] Introduction to Kotlin
- [ ] Null Safety In Kotlin

Devtools shortcuts
Firefox:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>

Chrome:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>

### CODE REVIEW

**Review by dvrylc — APPROVED** [review]
@iskandarzulkarnaien Apologies for the delay, I've verified that all the links work as intended 👍 

Just a thought - The first link of every toc doesn't seem very useful because it's simply the title of the article, and I can't think of a case where the user would want to jump there. Since the toc is supposed to be a table of the contents *within* the article, it doesn't seem like the title should be in there. What do you think?

**Review by Tejas2805 — CHANGES_REQUESTED** [review]
Hey! Good work. Just two things to take note of:

1) Can you re-trigger the CI once?

2) Don't think this is supposed to show up in the website version. Can update accoridngly?
Screen Shot 2020-02-21 at 11 43 26 PM

**Comment by iskandarzulkarnaien** [comment]
> 
> 
> @iskandarzulkarnaien Apologies for the delay, I've verified that all the links work as intended 👍
> 
> Just a thought - The first link of every toc doesn't seem very useful because it's simply the title of the article, and I can't think of a case where the user would want to jump there. Since the toc is supposed to be a table of the contents _within_ the article, it doesn't seem like the title should be in there. What do you think?

Thanks for reviewing! Its true that the first link is redundant, and honestly I kept it in purely to be consistent with the page nav e.g:
image

But seeing it is redundant (since unlike the page-nav the toc does not follow the user as they scroll), I'll get rid of it

**Comment by iskandarzulkarnaien** [comment]
> 
> 
> Hey! Good work. Just two things to take note of:
> 
>     1. Can you re-trigger the CI once?
> 
>     2. Don't think this is supposed to show up in the website version. Can update accoridngly?
>        Screen Shot 2020-02-21 at 11 43 26 PM

Good catch! I'll get rid of it. Thanks!

**Review by Tejas2805 — APPROVED** [review]

**Comment by iskandarzulkarnaien** [comment]
Thanks for the help @dvrylc and @Tejas2805 !
@damithc my PR is ready to be merged

**Comment by damithc** [comment]
Why is travis failing though?

**Comment by damithc** [comment]
> Why is travis failing though?

Never mind. Travis is not even supposed to run for PRs.

**Pull request merged**
